ActiveRecord::Base.send(:include, AdditionalAliases)
ActiveRecord::Base.send(:include, Calculator)
ActiveRecord::Base.send(:include, PickAndRejectHelper)
ActiveRecord::Base.send(:include, Searcher)
ActiveRecord::Base.send(:include, TouchesSelf)
