class AddKeys < ActiveRecord::Migration
  def change
    add_foreign_key "bids_labels", "bids", :name => "bids_labels_bid_id_fk"
    add_foreign_key "bids_labels", "labels", :name => "bids_labels_label_id_fk"
    add_foreign_key "projects_tags", "projects", :name => "projects_tags_project_id_fk"
    add_foreign_key "projects_tags", "tags", :name => "projects_tags_tag_id_fk"
    add_foreign_key "projects_teams", "projects", :name => "projects_teams_project_id_fk"
    add_foreign_key "projects_teams", "teams", :name => "projects_teams_team_id_fk"
    add_foreign_key "amendments", "users", :name => "amendments_poster_id_fk", :column => "poster_id"
    add_foreign_key "amendments", "projects", :name => "amendments_project_id_fk"
    add_foreign_key "bid_reviews", "bids", :name => "bid_reviews_bid_id_fk"
    add_foreign_key "bid_reviews", "users", :name => "bid_reviews_user_id_fk"
    add_foreign_key "bids", "users", :name => "bids_awarder_id_fk", :column => "awarder_id"
    add_foreign_key "bids", "users", :name => "bids_dismisser_id_fk", :column => "dismisser_id"
    add_foreign_key "bids", "projects", :name => "bids_project_id_fk"
    add_foreign_key "bids", "vendors", :name => "bids_vendor_id_fk"
    add_foreign_key "comments", "users", :name => "comments_user_id_fk"
    add_foreign_key "event_feeds", "events", :name => "event_feeds_event_id_fk"
    add_foreign_key "event_feeds", "users", :name => "event_feeds_user_id_fk"
    add_foreign_key "form_templates", "organizations", :name => "form_templates_organization_id_fk"
    add_foreign_key "labels", "projects", :name => "labels_project_id_fk"
    add_foreign_key "organization_team_members", "teams", :name => "organization_team_members_team_id_fk"
    add_foreign_key "organization_team_members", "users", :name => "organization_team_members_user_id_fk"
    add_foreign_key "project_revisions", "projects", :name => "project_revisions_project_id_fk"
    add_foreign_key "project_revisions", "users", :name => "project_revisions_saved_by_user_id_fk", :column => "saved_by_user_id"
    add_foreign_key "projects", "organizations", :name => "projects_organization_id_fk"
    add_foreign_key "projects", "users", :name => "projects_poster_id_fk", :column => "poster_id"
    add_foreign_key "questions", "users", :name => "questions_answerer_id_fk", :column => "answerer_id"
    add_foreign_key "questions", "users", :name => "questions_asker_id_fk", :column => "asker_id"
    add_foreign_key "questions", "projects", :name => "questions_project_id_fk"
    add_foreign_key "responses", "response_fields", :name => "responses_response_field_id_fk"
    add_foreign_key "responses", "users", :name => "responses_user_id_fk"
    add_foreign_key "saved_searches", "users", :name => "saved_searches_user_id_fk"
    add_foreign_key "teams", "organizations", :name => "teams_organization_id_fk"
    add_foreign_key "vendor_team_members", "users", :name => "vendor_team_members_user_id_fk"
    add_foreign_key "vendor_team_members", "vendors", :name => "vendor_team_members_vendor_id_fk"
    add_foreign_key "watches", "users", :name => "watches_user_id_fk"
  end
end
